var rasm2wasm=(()=>{var p=Object.defineProperty;var U=Object.getOwnPropertyDescriptor;var z=Object.getOwnPropertyNames,H=Object.getOwnPropertySymbols;var C=Object.prototype.hasOwnProperty,D=Object.prototype.propertyIsEnumerable;var T=(e,t,s)=>t in e?p(e,t,{enumerable:!0,configurable:!0,writable:!0,value:s}):e[t]=s,_=(e,t)=>{for(var s in t||(t={}))C.call(t,s)&&T(e,s,t[s]);if(H)for(var s of H(t))D.call(t,s)&&T(e,s,t[s]);return e};var K=(e,t)=>{for(var s in t)p(e,s,{get:t[s],enumerable:!0})},P=(e,t,s,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let r of z(t))!C.call(e,r)&&r!==s&&p(e,r,{get:()=>t[r],enumerable:!(n=U(t,r))||n.enumerable});return e};var Y=e=>P(p({},"__esModule",{value:!0}),e);var N={};K(N,{assemble:()=>G,cancel:()=>q,disassemble:()=>J,init_async:()=>f,listArchs:()=>j,progress:()=>b,reset:()=>W});function S(e){let t=!1,s=[],n=null,r=null,a=null,o=async(h,l)=>{i(),a||(a=new AbortController);let y=a.signal;t=!0;try{let d=await fetch(e+h,_({signal:y},l));if(d.status>=200&&d.status<300)return n=await u(d),n;throw new Error(d.statusText)}catch(d){return r=d,n=null,r}finally{t=!1}},u=async h=>{let l=h.body.getReader(),y=+h.headers.get("content-length"),d=0;for(;t;){let{done:g,value:L}=await l.read(),k={detail:{received:d,length:y,loading:t}},F=new CustomEvent("fetch-progress",k),O=new CustomEvent("fetch-finished",k);g?(t=!1,window.dispatchEvent(O)):(s.push(L),d+=L.length,window.dispatchEvent(F))}let A=new Uint8Array(d),M=0;for(let g of s)A.set(g,M),M+=g.length;return t=!1,A},i=()=>{t=!1,s=[],n=null,r=null,a=new AbortController};return{get:o,cancel:()=>{i(),a&&a.abort()}}}var w=1,E=class extends HTMLElement{connectedCallback(){w++,this.id="rasm2id"+w;let t=this.getAttribute("arch"),s=this.getAttribute("bits"),n=this.getAttribute("code");n||(n="");let r=this.getAttribute("data");r||(r="");let a=this.getAttribute("cpu");a||(a="");let o=this.getAttribute("addr");o||(o="0");let u=`
  <div style="background-color:#808080;border-radius:5px;padding:5px">
  <table style="width:100%"><tr><td>
  <textarea id="rasm2-code-`+this.id+'" style="font-family:monospace;background-color:black;color:white;box-sizing:border-box;width:98%;padding:5px;height:6em;margin:5px;border-radius:5px;resize:none">'+n+`</textarea>
      </td><td>
  <textarea id="rasm2-data-`+this.id+'" style="font-family:monospace;background-color:black;color:white;box-sizing:border-box;width:98%;padding:5px;height:6em;margin:5px;border-radius:5px;resize:none">'+r+`</textarea>
      </td></tr>
      <tr><td>
  <select id="rasm2-archs-`+this.id+`"></select>
  <select id="rasm2-bits-`+this.id+`">
  <option value="64">64</option>
  <option value="32">32</option>
  <option value="16">16</option>
  </select>
      </td></tr>
      </table>
  <div id="rasm2-orig-`+this.id+'" style="visibility:hidden">'+n+`</div>
  <div style="text-align:left; margin:5px">
  <div id="rasm2-arch-`+this.id+'" style="visibility:hidden">'+t+`</div>
  <div id="rasm2-addr-`+this.id+'" style="visibility:hidden">'+o+`</div>
  <div id="rasm2-cpu-`+this.id+'" style="visibility:hidden">'+a+`</div>
  <button onclick="rasm2wasm.assemble('`+this.id+`')">Assemble</button>
  <button onclick="rasm2wasm.disassemble('`+this.id+`')">Disassemble</button>
  <button onclick="rasm2wasm.listArchs('`+this.id+`')">Archs</button>
  <button onclick="rasm2wasm.reset('`+this.id+`')">Reset</button>
  </div>
  `,c=new DOMParser().parseFromString(u,"text/html");c.body.firstChild&&this.appendChild(c.body.firstChild)}constructor(){super();let t=document.createElement("div");t.style.padding="10px"}};window.customElements.define("rasm2-wasm",E);var x=class extends HTMLElement{connectedCallback(){w++,this.id="rasm2-wasm-progress";let n=new DOMParser().parseFromString("","text/html");n.body.firstChild&&this.appendChild(n.body.firstChild)}constructor(){super();let t=document.createElement("div");t.style.padding="10px"}};window.customElements.define("rasm2-wasm-progress",x);var{WASI:I}=window.Runno;function W(e){let t=document.getElementById("rasm2-shell-"+e);t.innerHTML="";let s=document.getElementById("rasm2-orig-"+e),n=document.getElementById("rasm2-code-"+e);n.value=s.innerHTML;let r=document.getElementById("rasm2-data-"+e);r.value=""}var m=null;var v=!1;function B(){if(v)return;v=!0,m=fetch("rasm2.wasm?v=5.8.8"),b({received:100,length:100,loading:!1}),v=!1}function q(){R();let e=document.getElementById("rasm2-wasm-progress"),t="";e.innerHTML=t}var R=()=>{};async function f(){try{let{get:e,cancel:t}=S("./");R=t,window.addEventListener("fetch-progress",s=>{b(s.detail)}),window.addEventListener("fetch-finished",s=>{b({received:100,length:100,loading:!1})}),m=await e("rasm2.wasm?v=5.8.8")}catch(e){console.error(e)}return B(),!0}function b(e){let t=0|e.received*100/e.length,s=document.getElementById("rasm2-wasm-progress");t===100?s.innerHTML="":s.innerHTML="<button onclick='rasm2wasm.cancel()'>cancel</button> <div style='border:2px solid black;background-color:grey;width:"+t+"px'> rasm2wasm.progress("+t+"%)</div>"}async function j(e){m==null&&await f();let t=I.start(m,{args:["rasm2","-Lq"],env:{SOME_KEY:"some value"},stdout:s=>{let n="";for(let r of s.trim().split(`
`))n+='<option value="'+r+'">'+r+`</option>
`;document.getElementById("rasm2-archs-"+e).innerHTML=n},stderr:s=>{console.error("stderr",s),div.innerHTML=s}})}async function G(e){m==null&&await f();let t=document.getElementById("rasm2-arch-"+e).innerHTML,s=document.getElementById("rasm2-bits-"+e).value,n=document.getElementById("rasm2-addr-"+e).innerHTML,r=document.getElementById("rasm2-cpu-"+e).innerHTML,a=document.getElementById("rasm2-code-"+e).value,o=document.getElementById("rasm2-data-"+e),u=document.getElementById("rasm2-archs-"+e).value;u&&(t=u),s||(s=64),n||(n=0);let i=[];r?i=["rasm2","-a",t,"-b",s,"-c",r,"-s",n,a]:i=["rasm2","-a",t,"-b",s,"-s",n,a],o.value="";let c=document.getElementById("rasm2-shell-"+e),h=I.start(m,{args:i,env:{SOME_KEY:"some value"},stdout:l=>{o.value+=l},stderr:l=>{console.error("stderr",l),c.value+=l}});B()}async function J(e){m==null&&await f();let t=document.getElementById("rasm2-arch-"+e).innerHTML,s=document.getElementById("rasm2-bits-"+e).value,n=document.getElementById("rasm2-addr-"+e).innerHTML,r=document.getElementById("rasm2-cpu-"+e).innerHTML,a=document.getElementById("rasm2-data-"+e).value,o=document.getElementById("rasm2-code-"+e),u=document.getElementById("rasm2-shell-"+e),i=document.getElementById("rasm2-archs-"+e).value;i&&(t=i),s||(s=64),n||(n=0);let c=[];r?c=["rasm2","-a",t,"-b",s,"-c",r,"-s",n,"-d",a]:c=["rasm2","-a",t,"-b",s,"-s",n,"-d",a];let h=I.start(m,{args:c,env:{SOME_KEY:"some value"},stdout:l=>{o.value=l},stderr:l=>{console.error("stderr",l),document.getElementById("rasm2-shell-"+e).value=l}});B()}return Y(N);})();
